POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "jhordart",
    "name": "samir arteaga",
    "password": "12345"
}

###
GET http://localhost:3001/api/users 

###

DELETE http://localhost:3001/api/users/652cbed4619d106d0bf55405
